# ==========================================================
# Globalne ustawienia serwera
# ==========================================================

# Katalog główny instalacji Apache
# ServerRoot "/etc/httpd"

# Port, na którym serwer nasłuchuje żądań
Listen 80

# Ładowanie niezbędnych modułów bazowych
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so

# Użytkownik i grupa, z uprawnieniami których działa proces potomny
User www-data
Group www-data

# Adres e-mail administratora systemu
ServerAdmin admin@example.com

# Blokada dostępu do całego systemu plików (zabezpieczenie)
# <Directory />
#     AllowOverride none
#     Require all denied
# </Directory>

<VirtualHost *:80>
    # Nazwa domeny powiązana z tym hostem
    ServerName 127.0.0.1
    # ServerAlias example.com

    # Katalog główny, z którego serwowane są pliki strony
    DocumentRoot "/var/www/html/public"

    # Domyślny plik indeksu w katalogu
    # DirectoryIndex index.html

    # Uprawnienia i zachowanie dla katalogu DocumentRoot
    <Directory "/var/www/html/public">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    # Definicja i lokalizacja logów błędów oraz dostępu
    ErrorLog "logs/example_error.log"
    CustomLog "logs/example_access.log" common
</VirtualHost>
